Import('env')
env = env.Clone()

env.AppendUnique(CPPPATH=['#src/ngn'])
env.ParseConfig('pkg-config --cflags --libs glfw3')

cmd = env.Program('rrr', Glob('*.cpp'), LIBS=['ngn'], LIBPATH=['#install'])
env.Install('#install', cmd)
