import sys

Import('env')
env = env.Clone()

env.AppendUnique(CPPPATH=['#src/ngn','#libs/glm'])
env.ParseConfig('pkg-config --cflags --libs glfw3')

# Set up rpath on Linux so we can find the shared libraries.
if sys.platform.startswith('linux'):
    env.AppendUnique(LINKFLAGS=['-z', 'origin'])
    env.AppendUnique(RPATH=env.Literal('\\$$ORIGIN'))

cmd = env.Program('test_pool', ['test_pool.cpp'], LIBS=['ngn'], LIBPATH=['#install'])
env.Install('#install', cmd)
