import sys

Import('env')
env = env.Clone()

env.AppendUnique(CPPPATH=['#libs/glm'])
# Set install_name on Mac OS X so we can find the shared library.
if sys.platform == 'darwin':
    env.AppendUnique(LINKFLAGS=['-install_name', '@executable_path/libngn.dylib'])

lib = env.SharedLibrary('ngn', Glob('*.cpp'))
env.Install('#install', lib)
